<template>
  <div class="page" id="content">
    <div class="title">Check on Learning - LSA #1</div>
    <div class="body-text">Complete a Check on Learning to summarize the Learning Activity and assess your understanding of the material presented in this LSA.</div>
    <div class="content-box">

      <div class="question">
        <multi-comp :question="'Q1. MWR programs offered at Army garrisons are based on what?'" :choices="[
        'Garrison commander\'s discretion.',
        'The needs of the authorized patrons who work and reside there.',
        'Available funds that are locally generated by MWR programs.',
        'Authorized and available APFs and nonappropriated funds (NAFs).']" :correctAnswer="'The needs of the authorized patrons who work and reside there.'" />
      </div>
      <div class="question">
        <multi-comp :question="'Q2. What are the objectives of the MWR Program?'" :choices="[
        'Support combat readiness and effectiveness.',
        'Support recruitment and retention of quality personnel.',
        'Provide leisure time activities, which support a quality of life commensurate with generally accepted American values.',
        'Promote and maintains the mental and physical well-being of authorized personnel.',
        'Foster community pride, Soldier morale, and Family wellness and promotes unit esprit de corps.',
        'Ease the impact of unique aspects of military life, such as frequent relocations and deployment.',
        'All the Above']" :correctAnswer="'All the Above'" />
      </div>
    </div>


  </div>

  <!-- NOTES -->
  <Teleport to="#notes-comp">
    <p>
      N/A
    </p>
  </Teleport>

</template>

<script>
import multiComp from '@/components/questions/multiComp.vue'

export default {
  name: 'slideOne',
  mounted() {
    this.$store.commit('pageloaded')
  },
  components: {
    multiComp,
  },
}
</script>
<style scoped>
.page {
  overflow: scroll;
}

.title {
  /* border: 1px solid red; */
  margin-bottom: 20px;
}
.body-text {
  font-size: 1.1rem;
}
.graphic {
  width: 75%;
}
.body-text {
  text-align: center;
  margin-bottom: 30px;
}
.content-box {
  height: 90%;
  width: 100%;
  display: flex;
  flex-direction: column;
  /* border: 1px solid blue; */
}
.question {
  height: 100%;
  width: 100%;
  margin-bottom: 20px;
}
</style>