<template>
  <div class="page" id="content">
    <div class="title">Morale, Welfare, & Recreation (MWR) Program (2 of 3)</div>
    <div class="body-text">
      <ul>
        <li>The Army MWR program is a quality-of-life program that directly supports readiness by providing a variety of community, Soldier, and Family support programs, activities, and services</li>
        <li>MWR programs offered at Army garrisons are based on the needs of authorized patrons who work and reside there</li>
        <li>MWR programs are classified by category, which are determined by their effect on the military mission and their ability to generate revenue</li>
      </ul>
    </div>
  </div>

  <!-- NOTES -->
  <Teleport to="#notes-comp">
    <p>
      Included are social, fitness, recreational, educational, and other programs and activities that enhance community life, foster Soldier and unit readiness, promote mental and physical fitness, and generally provide a working and living environment that attracts and retains quality Soldiers. 
    </p>

    <p>
      Programs are managed by garrison commanders within the framework of authorized and available APFs and nonappropriated funds (NAFs). Nonappropriated funds are those funds that are locally generated by MWR programs or provided by Region directors and/or the Army Morale, Welfare, and Recreation Fund (AMWRF). AAFES dividends are also a source of NAFs. 
    </p>

    <p>
      Each MWR program is classified by category.  Categories are determined by their effect on the military mission and their ability to generate revenue. 
    </p>

    <p>
      <b>For additional information, refer to AR 215-1, Para. 1-9.</b>
    </p>
  </Teleport>

</template>

<script>

export default {
  name: 'slideOne',
  mounted() {
    this.$store.commit('pageloaded')
  }
}
</script>
<style scoped>
.graphic {
  width: 75%;
}
.body-text {
  text-align: left;
}
li {
  margin-bottom: 15px;
}
</style>